// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoFhR6h9HcFUQJseuqVvStOk_SDpQx-J8',
    appId: '1:374347850092:web:443deb10a329abc1829349',
    messagingSenderId: '374347850092',
    projectId: 'fast-konseling-f4cf2',
    authDomain: 'fast-konseling-f4cf2.firebaseapp.com',
    storageBucket: 'fast-konseling-f4cf2.firebasestorage.app',
    measurementId: 'G-YRQRW2CTS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTS2MexRtknnXVo9YORaLjw4xoFFgrr_Q',
    appId: '1:374347850092:android:725b92c8fb595007829349',
    messagingSenderId: '374347850092',
    projectId: 'fast-konseling-f4cf2',
    storageBucket: 'fast-konseling-f4cf2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5E__DucxtrBcnL9i1hXL7dPFTqhOMcFY',
    appId: '1:374347850092:ios:ecd07fe5897edafd829349',
    messagingSenderId: '374347850092',
    projectId: 'fast-konseling-f4cf2',
    storageBucket: 'fast-konseling-f4cf2.firebasestorage.app',
    iosBundleId: 'com.example.fastKonseling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5E__DucxtrBcnL9i1hXL7dPFTqhOMcFY',
    appId: '1:374347850092:ios:ecd07fe5897edafd829349',
    messagingSenderId: '374347850092',
    projectId: 'fast-konseling-f4cf2',
    storageBucket: 'fast-konseling-f4cf2.firebasestorage.app',
    iosBundleId: 'com.example.fastKonseling',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoFhR6h9HcFUQJseuqVvStOk_SDpQx-J8',
    appId: '1:374347850092:web:dbd012d616d152e1829349',
    messagingSenderId: '374347850092',
    projectId: 'fast-konseling-f4cf2',
    authDomain: 'fast-konseling-f4cf2.firebaseapp.com',
    storageBucket: 'fast-konseling-f4cf2.firebasestorage.app',
    measurementId: 'G-XNGQJEW1VY',
  );
}
